
name: 'dbt_snowflake_aws'
version: '1.0.0'

profile: 'dbt_snowflake_aws'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_aws:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      +materialized: table
      +schema: bronze #custom schema for bronze layer
    silver:
      +materialized: table
      +schema: silver #custom schema for silver layer
    gold:
      +materialized: table
      +schema: gold #custom schema for gold layer
      epheremal:
        +materialized: ephemeral
